console.log("Question 21");
let a=10;
let b=2;
console.log(a+b);
console.log(a-b);
console.log(a*b);
console.log(a/b);
console.log(a%b);
console.log("Question 22");
let width=5;
let height=10;
console.log("Area of Rectangle is "+(width*height));
console.log("Question 22");
a+=2;
console.log(a);
a-=2;
console.log(a);
a*=2;
console.log(a);
a/=2;
console.log(a);
a%=2;
console.log(a);
a++;
console.log(a);
a--;
console.log(a);
